name: Compilar Matinha RP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar reposit√≥rio
        uses: actions/checkout@v3

      - name: Instalar compilador Pawn
        run: |
          sudo apt update
          sudo apt install -y git make gcc
          git clone https://github.com/pawn-lang/compiler.git
          cd compiler
          make

      - name: Compilar GM
        run: |
          cd ..
          ./compiler/pawncc/gm.pwn -iinclude -o gamemode.amx

      - name: Salvar AMX
        uses: actions/upload-artifact@v4
        with:
          name: Matinha-RP-AMX
          path: gamemode.amx
