name: Compilar Matinha RP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Baixar compilador Pawn pré-compilado
        run: |
          wget https://github.com/pawn-lang/compiler/releases/download/v3.3.356/pawnc-3.3.356-linux.tar.gz -O pawn.tar.gz
          tar -xzf pawn.tar.gz
          chmod +x pawncc/pawncc

      - name: Compilar GM
        run: |
          ./pawncc/pawncc gm.pwn -iinclude -o gamemode.amx

      - name: Salvar AMX
        uses: actions/upload-artifact@v4
        with:
          name: Matinha-RP-AMX
          path: gamemode.amx
